config/routes.rb
GiddyVote::Application.routes.draw do
  resources :votes

  root 'votes#index'

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  validates :email, :uniqueness => true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }
  validates_presence_of :coffee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
    respond_to do |format|
      format.html { redirect_to action: 'new', notice: 'Thank you.' }
    end
  end

  # GET /votes/new
  def new
    @vote = Vote.new
    @oro = Vote.where("coffee = 'Oro-Espresso'").count
    @rock = Vote.where("coffee = 'Rock-a-billy'").count
  end

  # GET /votes/1/edit
  def edit
    respond_to do |format|
      format.html { redirect_to action: 'new', notice: 'Thank you.' }
    end
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        # format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.html { redirect_to action: 'new', notice: 'Vote was succefully created.' }
        format.json { render action: 'show', status: :created, location: @vote }
      else
        format.html { render action: 'new' }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      format.html { redirect_to action: 'new', notice: 'Thank you.' }
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    respond_to do |format|
      format.html { redirect_to action: 'new', notice: 'Thank you.' }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_vote
    @vote = Vote.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vote_params
    params.require(:vote).permit(:coffee, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/votes/_banner.html.erb
<div class="center_me">
  <div class="large-10 large-offset-1">
    <div class="large-5 columns">
      <div class="other_circle green_back">
        <%= @rock %>
      </div>
      <h4>Rock-a-billy</h4>
    </div>

    <div class="large-5 columns">
      <div class="other_circle green_back">
        <%= @oro %>
      </div>
      <h4>Oro-Espresso</h4>
    </div>
  </div>
</div>

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>
      <ul>
        <% @vote.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field row">
    <div class="large-4 large-offset-4">
      <%= f.text_field :email, placeholder: "Email Address", required: :true %>
    </div>
    <div class="actions row">
      <div class="large-2 large-offset-5">
        <%= f.submit "Cast Your Vote", :class => "button radius" %>
      </div>
    </div>
  </div>
  <div class="field row selection">
    <div class="large-10 large-offset-1">
      <div class="large-5 columns">
        <label class="panel round_box darken">
          <div class="center_me">
            <div class="other_circle green_back">
              <%= @rock %>
            </div>
            <div class="coffee_text brown_text">
              Rock-a-Billy <%= f.radio_button(:coffee, "Rock-a-billy") %>
            </div>
            <%= image_tag("IMG_ROCK.png") %>
          </div>
        </label>
      </div>
      <div class="large-5 columns">
        <label class="panel round_box darken">
          <div class="center_me">
            <div class="other_circle green_back">
              <%= @oro %>
            </div>
            <div class="coffee_text brown_text">
              Cafe Oro <%= f.radio_button(:coffee, "Oro-Espresso") %>
            </div>
            <%= image_tag("IMG_ORO.png") %>
          </div>
        </label>
      </div>
    </div>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <thead>
    <tr>
      <th>Coffee</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.coffee %></td>
        <td><%= vote.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<%- if notice %>
  <div class="alert-box"><%= notice %></div>
<% end %>
<div class="row center_me">
  <div class="large-10 large-offset-1">
    <h1 class="header brown_text">Espresso Showdown</h1>
    <h3 class="subheader">The Giddy Goat Coffeehouse</h3>
  </div>
</div>
<div class="row">
  <div class="large-12 center_me">
    <p><strong>Please Note:</strong> We are keeping both espresso blends but we value your opinion on which you like best.</p>
  </div>
  <div class="round_box gray_back">
    <div class="center_me">
      <h2><small>Let us know which espresso blend you like the best.</small></h2>
    </div>
    <%= render 'form' %>
  </div>
  <div class="row">
  </div>
</div>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Coffee:</strong>
  <%= @vote.coffee %>
</p>

<p>
  <strong>Email:</strong>
  <%= @vote.email %>
</p>

<%= link_to 'Back', votes_path %>